Fix broken release/publish process
bintray-sbt 0.1.1 was causing issues like:
[trace] Stack trace suppressed: run last job-server-extras/*:bintrayEnsurePackage for the full output.
[error] (job-server-extras/*:bintrayEnsurePackage) java.lang.NoSuchMethodError: org.json4s.Implicits.string2jvalue(Ljava/lang/String;)Lorg/json4s/JsonAST$JString;

Also, the lsync step was broken always returning 404.